[build]
  publish = "dist/public" 
  command = "npm ci --include=dev && npx vite build --config vite.config.prod.ts && cp _redirects dist/public/"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/tasks"
  to = "/.netlify/functions/tasks"
  status = 200

[[redirects]]
  from = "/api/tasks/*"
  to = "/.netlify/functions/tasks"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_ENV = "production"
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"